### ISSUE TITLE
Migrate examples to site-webdev/examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2_api_examples#8]
- [x] common/pipes - https://github.com/dart-lang/site-webdev/pull/505
- [x] testing - https://github.com/dart-lang/site-webdev/pull/505
- [x] leave placeholders telling folks where to find the examples
- [x] mark this repo as deprecated

cc @kevmoo @kwalrath @matanlurey

**Comment by kevmoo** [comment]
Request: make sure you leave placeholders so folks hitting these can find the code

Also: maybe add a bullet for marking this repo as deprecated – we can set a timeline to delete it in x months
